### ISSUE TITLE
Duplicate "You are a helpful assistant." system message

### ISSUE THREAD

**Issue by zainhoda** [kydycode/chatgpt-3.5-turbo#4]
The message log initially contains a "You are a helpful assistant." system message.
https://github.com/kydycode/chatgpt-3.5-turbo/blob/58721516a1a37fd72ad78ca2baf717b3bec9ae5e/main.py#L30-L32

This appears to be a duplicate:
https://github.com/kydycode/chatgpt-3.5-turbo/blob/58721516a1a37fd72ad78ca2baf717b3bec9ae5e/main.py#L45

**Comment by vitalio-sh** [comment]
thanks!

**Comment by zainhoda** [comment]
Thank you for putting this together! It's super helpful!
